### ISSUE TITLE
__gettotalrep() doesn't work for users with 0 posts

### ISSUE THREAD

**Issue by sej917** [rbonick/care-tags_scripts#12]
This should probably be fixed so that, instead of throwing an exception, it returns a total rep of 0.

**Comment by rbonick** [comment]
Oh is that the cause of the bug? People had 0 rep given?

**Comment by sej917** [comment]
whoops, i misstyped the issue title. The bug is for users with zero posts, not zero rep given.

**Comment by sej917** [comment]
This is fixed now.
